name: react-build
on:
  push: 
    branches: 
      - develop
env:
  AGE: 39
jobs:
  build:
     runs-on: ubuntu-latest
     env:
       SURNAME: RAYUDU
     steps:
       - name: checkout 
         uses: actions/checkout@v2
       - name: custom-step
         run: |
           echo "Hello $SURNAME $MYNAME age $AGE  ${{ secrets.SONAR_TOKEN }}"
           echo '${{ runner.os }}'
         env:
           MYNAME: Subrahmanyam
       - name: Use Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '12.x'
       - run: npm install
       - run: npm run build --if-present
       - run: npm test    

