name: react-build
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout 
         uses: actions/checkout@v2
       - name: custom-step
         run: echo "Hello ${{MYNAME}}" 
         env:
           MYNAME: Rayudu 

