name: repo-dispatch
on:
  repository_dispatch:
    types: [opened, deleted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test 123
        uses: actions/checkout@v1
      - name: test 321  
        run: echo "testing"    
