name: upload-workflow
on: 
  push:
    branches: [develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create-files
        run: |
          mkdir downloads
          cd downloads
          echo 'alpha' > alpha.html
          echo 'bravo' > bravo.html
          echo 'beta' > beta.html
          cd ..
      - name: use the upload artifact github action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads
      - name: create download folder
        run: |
          mkdir downloadfiles
          cd downloadfiles    
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact    
      - name: Display structure of downloaded files
        run: ls -R